config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :leads, :statuses, :species, :shrines
=======
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  resources :leads, :statuses, :species
>>>>>>> 89841beef1f168e378704cb177dbef2633312f76

  root 'home#index'

end

app/models/shrine.rb
class Shrine < ActiveRecord::Base
<<<<<<< HEAD
	# Friendly url by id
	extend FriendlyId
  	friendly_id :name, use: :slugged

  	# Filterrific
	filterrific(
		#default_filter_params: { with_statuses_id: 'statuses_id_desc' },
		available_filters: [
			:search_query,
			#:with_country_id,
			#:with_created_at_gte
		]
	)
  	
	has_many :species
	validates :name,:description, presence: true

	scope :search_query, lambda { |query| 
		return nil  if query.blank?
		# condition query, parse into individual keywords
		terms = query.downcase.split(/\s+/)
		# replace "*" with "%" for wildcard searches,
		# append '%', remove duplicate '%'s
		terms = terms.map { |e|
			(e.gsub('*', '%') + '%').gsub(/%+/, '%')
		}
		# configure number of OR conditions for provision
		# of interpolation arguments. Adjust this if you
		# change the number of OR conditions.
		num_or_conditions = 2
		where(
			terms.map {
				or_clauses = [
					"LOWER(shrines.name) LIKE ?",
					"LOWER(shrines.description) LIKE ?",
				].join(' OR ')
				"(#{ or_clauses })"
			}.join(' AND '),
			*terms.map { |e| [e] * num_or_conditions }.flatten
		)
	}

	attr_accessor :picture

	after_save :save_picture_profile, if: :picture 
	def save_picture_profile
		filename 	= picture.original_filename
		folder		= "public/shrines/#{id}/profile"

		FileUtils::mkdir_p folder

		f = File.open File.join(folder, filename), "wb"
		f.write picture.read()
		f.close

		self.picture = nil

		update image: filename
	end	
=======
	
>>>>>>> 89841beef1f168e378704cb177dbef2633312f76
end

app/controllers/shrines_controller.rb
class ShrinesController < ApplicationController
	def index
		@navbar = true

		# Filterrific
		@filterrific = initialize_filterrific(
			Shrine, 
			params[:filterrific],
			persistence_id: 'shared_key',
			) or return 
			@shrines = @filterrific.find.paginate(:page => params[:page], :per_page => 10)

		# Ajax
		respond_to do |format|
			format.html
			format.js
		end
	end
	def create
		@shrines = Shrine.new lead_params
		respond_to do |format|
			if Shrine.find_by_name(@shrines.name).blank?			
				if @result = @shrines.save
					format.html { redirect_to :back }
					format.js
				else
					format.html { redirect_to :back, @shrines.errors } 
					format.js
				end			
			else 
				format.html { redirect_to :back, @shrines.errors  }
				format.js
			end
		end
	end
	def new 
		@navbar = true
	end

	def show
		@shrines = Shrine.friendly.find(params[:id])
		@title = @shrines.name
		@navbar = true
	end

	private 

	def lead_params
		params.require(:shrine).permit(:name, :picture, :description)
	end
end

app/helpers/shrines_helper.rb
module ShrinesHelper
end

app/views/shrines/_list.html.erb
<section class="list-animals shrines-section" id="filterrific_re">
	<div class="container">
		<div class="row">
			<article class="list-item">
				<ul class="tile-gallery">
			<% if shrines.empty? %> 
					<p>Lo siento no se encontró el santuario que buscas <%= link_to "Agrégalo", new_shrine_path %></p>			
			<% else %>
				<% shrines.each do |shrine| %>
					<li class="col-lg-6 col-md-6 col-sm-6 column-6">
						<div class="specie-item">
							<figure>
								<a href=""><%= image_tag "/shrines/#{shrine.id}/profile/#{shrine.image}" if shrine.image? %></a>
							</figure>
							<div class="details-of-specie">
								<div class="head-name">
									<h3><a href=""><%= shrine.name %></a></h3>
								</div>
								<br>
								<div class="specie-habitat">
									<%= link_to "Ver Perfil", shrine, class: 'btn btn-warning' %>
								</div>
							</div>
						</div>
					</li>
				<% end %>						
			<% end %>				
				</ul>
			</article>
		</div>
		<%= will_paginate shrines , renderer: BootstrapPagination::Rails %>
	</div>
</section>

app/views/shrines/create.js.erb
<% if @result %>
	$('#response').addClass('save-success');
	$('#response').text('Santuario agregada con exito!');
<% else %>	
	$('#response').addClass('save-fail');
	$('#response').text('No pudimos agregar el Santuario intente otra!');
<% end %>

app/views/shrines/index.html.erb
<section class="filter">
  <div class="container">
    <div class="row">
      <%= form_for_filterrific @filterrific do |f| %>
        <div class="col-lg-3">
          <div class="form-group">
            <p>Filtrar Santuarios:</p>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="form-group">
            <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
            <%= f.text_field(:search_query, class: 'filterrific-periodically-observed form-control', placeholder: 'Buscar Santuario') %>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="form-group">
            <%= link_to('Limpiar',reset_filterrific_url, class: 'btn btn-info') %>
          </div>
        </div>
        <%# add an automated spinner to your form when the list is refreshed %>
        <%= render_filterrific_spinner %>
      <% end %>
    </div>
  </div>
</section>
<%= render(partial: 'shrines/list', locals: { shrines: @shrines }) %>

app/views/shrines/index.js.erb
<% js = escape_javascript(
  render(partial: 'shrines/list', locals: { shrines: @shrines })
) %>
$("#filterrific_re").html("<%= js %>");

app/views/shrines/new.html.erb
<section class="create-form">
	<div class="container">
		<article class="new">
			<h3>Agregar Categoria de Extinción</h3>
			<%= form_for Shrine.new,:remote => true do |f| %>
				<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
				<div class="form-group">
					<%= f.text_field :name, :class => 'form-control', :placeholder => 'Nombre de Santurio' %>
				</div>
				<div class="form-group">
					<%= f.text_area :description, class: 'form-control ckeditor' %>
				</div>
				<div class="form-group">
					<%= f.file_field :picture, :class => 'form-control' %>
				</div>						
				<div class="form-group">
					<%= f.button 'Agregar', {class: 'btn btn-info'} %>
				</div>
				<p id="response"></p>
			<% end %>
		</article>
	</div>
</section>

app/views/shrines/show.html.erb
<section class="specie-profile">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 sidebar-specie">
				<figure>
					<%= image_tag "/shrines/#{@shrines.id}/profile/#{@shrines.image}"%>
				</figure>
				<ul>
					<li class="active">
						<a href="#desc">Descripción</a>
					</li>
				</ul>
			</div>
			<div class="col-lg-9 content-sidebar">
				<article class="spec">
					<h3><%= @shrines.name %></h3>
					<div id="desc" class="info-specie">
						<h4>Vista General</h4>
						<%= @shrines.description.html_safe %>
					</div>
					<div id="spot-im-frame-inpage" data-post-id="<%= @shrines.id %>"></div>
				</article>							
			</div>				
		</div>
	</div>
</section>