config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :leads, :statuses, :species, :shrines
=======
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  resources :leads, :statuses, :species
>>>>>>> 89841beef1f168e378704cb177dbef2633312f76

  root 'home#index'

end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	def index
		#@species = Specie.paginate(:page => params[:page], :per_page => 10)
		@navbar = true
<<<<<<< HEAD

		# Filterrific
		@filterrific = initialize_filterrific(
			Specie, 
			params[:filterrific],
			select_options: {
				with_statuses_id: Status.options_for_select,
				with_families_id: Family.options_for_select
			},
			persistence_id: 'shared_key',
			) or return 
			@species = @filterrific.find.paginate(:page => params[:page], :per_page => 10)

		# Ajax
		respond_to do |format|
			format.html
			format.js
		end

=======
>>>>>>> 89841beef1f168e378704cb177dbef2633312f76
	end

	def create
		@species = Specie.new lead_params
		respond_to do |format|
			if Specie.find_by_name(@species.name).blank?			
				if @result = @species.save
					format.html { redirect_to :back }
					format.js
				else
					format.html { redirect_to :back, @species.errors } 
					format.js
				end			
			else 
				format.html { redirect_to :back, @species.errors  }
				format.js
			end
		end
	end

	def new 
		@navbar = true
	end

	def show
		@specie = Specie.friendly.find(params[:id])
		@title = @specie.name
		@navbar = true
	end

	private 

	def lead_params
		params.require(:specie).permit(:name, :scientific_name, :country, :population, :statuses_id, :shrines_id, :families_id, :need, :picture, :habitat, :description, :nutrition, :threats)
	end

end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/species/_list.html.erb
<section class="list-animals" id="filterrific_results">
  <div class="container">
    <div class="row">
    <%#page_entries_info species %>
      <article class="list-item">
        <ul class="tile-gallery">
      <% if species.empty? %>
        <p>Lo siento no se encontró la especie que buscas <%= link_to "Agrégalo", new_species_path %></p>
      <% else %>
        <% species.each do |specie| %>
          <li class="col-lg-6 col-md-6 col-sm-6 column-6">
            <div class="specie-item">
              <figure>
                <a href=""><%= image_tag "/species/#{specie.id}/profile/#{specie.image}" if specie.image? %></a>
              </figure>
              <div class="details-of-specie">
                <div class="head-name">
                  <h3><a href=""><%= specie.name %></a></h3>
                  <p><%= specie.scientific_name %></p>
                </div>
                <div class="species-habitat">
                  <p>Habitat: <span>Montañas, America del Sur</span></p>
                  <p>País: <span><%= specie.country %></span></p>
                  <p>Categoria: <span><%= Status.find(specie.statuses_id).name %></span></p>
                </div>
              </div>
              <div class="btn-details">
                <%= link_to ">", specie %>
              </div>
            </div>
          </li>
        <% end %>   
      <% end %>
        </ul>
      </article>
    </div>
      <%= will_paginate species, renderer: BootstrapPagination::Rails %>     
  </div>  
</section>

app/views/species/create.js.erb
<% if @result %>
	$('#response').addClass('save-success');
	$('#response').text('Especie agregada con exito!');
<% else %>	
	$('#response').addClass('save-fail');
	$('#response').text('No pudimos agregar la especie intente otra!');
<% end %>

app/views/species/index.html.erb
<section class="filter">
  <div class="container">
    <div class="row">
      <%= form_for_filterrific @filterrific do |f| %>
        <div class="col-lg-2">
          <div class="form-group">
            <p>Filtrar Especies:</p>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="form-group">
            <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
            <%= f.text_field(:search_query, class: 'filterrific-periodically-observed form-control', placeholder: 'Buscar Especie') %>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="form-group">
            <%= f.select(:with_statuses_id, @filterrific.select_options[:with_statuses_id],
            { include_blank: "- Seleccione la Categoria-" }, class: 'form-control') %>            
          </div>
        </div>
        <div class="col-lg-3">
          <%= f.select(:with_families_id, @filterrific.select_options[:with_families_id],
            { include_blank: "- Seleccione Familia-" }, class: 'form-control') %>          
        </div>
        <div class="col-lg-1">
          <div class="form-group">
            <%= link_to('Limpiar',reset_filterrific_url, class: 'btn btn-info') %>
          </div>
        </div>
        <%# add an automated spinner to your form when the list is refreshed %>
        <%= render_filterrific_spinner %>
      <% end %>
    </div>
  </div>
</section>
<%= render(partial: 'species/list', locals: { species: @species }) %>

app/views/species/index.js.erb
<% js = escape_javascript(
  render(partial: 'species/list', locals: { species: @species })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/species/new.html.erb
<section class="create-form">
	<div class="container">
		<article class="new">
			<h3>Agregar Nueva Especie</h3>
			<%= form_for Specie.new, url: {action: "create"},:html => { :multipart => true }, :remote => true do |f| %>
				<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
				<div class="form-group">
					<%= f.text_field :name, :class => 'form-control', :placeholder=> 'Nombre' %>
				</div>
				<div class="form-group">
					<%= f.text_field :scientific_name, :class => 'form-control', :placeholder=> 'Nombre Cientifico' %>
				</div>
				<div class="form-group">
					<%= f.country_select :country, :class => 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.text_field :population, :class => 'form-control', :placeholder=> 'Poblacion' %>
				</div>
				<div class="form-group">
					<%= f.label 'Seleccione la categoria de extinción:' %> 
					<%= f.select :statuses_id, options_from_collection_for_select(Status.all, :id, :name), :class => "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label 'Seleccione  familia:' %> 
					<%= f.select :families_id, options_from_collection_for_select(Family.all, :id, :name), :class => "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label 'Seleccione un santuario:' %> 
					<%= f.select :shrines_id, options_from_collection_for_select(Shrine.all, :id, :name), :class => "form-control" %>
				</div>
				<div class="form-group">					
					<%= f.text_field :need, :class => 'form-control', :placeholder=> '¿Qué necetita la especie ?' %>
				</div>
				<div class="form-group">
					<%= f.file_field :picture, :class => 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.text_area :habitat, :class => 'form-control', :placeholder => 'Habitat de la especie...' %>
				</div>
				<div class="form-group">
					<%= f.label 'Descripcion de la especie:' %> 
					<%= f.text_area :description, :class => 'form-control ckeditor' %>
				</div>				
				<div class="form-group">
					<%= f.label 'Descripcion de la alimentación:' %> 
					<%= f.text_area :nutrition, :class => 'form-control ckeditor' %>
				</div>	
				<div class="form-group">
					<%= f.label 'Amenaza de extincion:' %> 
					<%= f.text_area :threats, :class => 'form-control ckeditor' %>
				</div>							
				<div class="form-group">
					<%= f.button 'Agregar', {class: 'btn btn-info'} %>
				</div>
				<p id="response"></p>
			<% end %>
		</article>
	</div>
</section>

app/views/species/show.html.erb
<section class="specie-profile">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 sidebar-specie">
				<figure>
					<%= image_tag "/species/#{@specie.id}/profile/#{@specie.image}"%>
				</figure>
				<ul>
					<li class="active">
						<a href="#desc">Descripción</a>
					</li>
					<li>
						<a href="#habitat">Habitat</a>
					</li>
					<li>
						<a href="#diet">Dieta</a>
					</li>
					<li>
						<a href="#threat">Amenaza</a>
					</li>
				</ul>
			</div>
			<div class="col-lg-9 content-sidebar">
				<article class="spec">
					<h3><%= @specie.name %></h3>
					<p><%= @specie.scientific_name %></p>
					<div class="detail">
						<div class="col-lg-4 column-4">
							<div class="circle ep">
								<p><%= Status.find(@specie.statuses_id).prefix %></p>
							</div>
							<div class="wrap">
								<p>ESTADO</p>
								<span><%= Status.find(@specie.statuses_id).name %></span>
							</div>						
						</div>
						<div class="col-lg-4 column-4">
							<div class="icono">
								<i class="icon fish-group-ico"></i>
							</div>							
							<div class="wrap">
								<p>POBLACIÓN</p>
								<span><%= @specie.population %></span>
							</div>
						</div>
						<div class="col-lg-4">
<<<<<<< HEAD
						<% if @specie.families_id %>
							<p>Familia</p>
							<span><%= Family.find(@specie.families_id).name %></span> 
						<%end%>
=======
							<a href="">Adoptar</a>
>>>>>>> 89841beef1f168e378704cb177dbef2633312f76
						</div>
					</div>
					<div id="desc" class="info-specie">
						<h4>Vista General</h4>
						<%= @specie.description.html_safe %>
					</div>
					<div id="habitat" class="info-specie">
						<h4>Habitat</h4>
						<p><%= @specie.habitat %></p>
					</div>
					<div id="diet" class="info-specie">
						<h4>Alimentación</h4>
						<%= @specie.nutrition.html_safe %>
					</div>
					<div id="threat" class="info-specie">
						<h4>Amenzas</h4>
						<%= @specie.threats.html_safe %>
					</div>
					<div id="spot-im-frame-inpage" data-post-id="<%= @specie.id %>"></div>
				</article>							
			</div>				
		</div>
	</div>
</section>