config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :leads, :statuses, :species, :shrines
=======
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  resources :leads, :statuses, :species
>>>>>>> 89841beef1f168e378704cb177dbef2633312f76

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta charset="utf-8">
    <title><%= @title + " |" if @title %> Yorescato</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= csrf_meta_tags %>
<<<<<<< HEAD

=======
>>>>>>> 89841beef1f168e378704cb177dbef2633312f76
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-65887718-1', 'auto');
	ga('send', 'pageview');

</script>
<script type="text/javascript">!function(t,e,n){
function a(t){var  a=e.createElement("script");a.type="text/javascript" ,a.async=!0,a.src=("https:"===e.location.protocol?"https":"http")+":"+n,(t||e.body||e.head).appendChild(a)}function o(){var  t=e.getElementsByTagName("script"),n=t[t.length-1];return n.parentNode} var  p=o();t.spotId="sp_n5CnvPP2",t.parentElement=p,a(p)}(window.SPOTIM={},document,"//www.spot.im/launcher/bundle.js");</script>
</head>

<body>
<div id="fullpage">
<% if notice %><div class="alert alert-success" role="alert"><%= notice %></div><% end %>
<% if alert %><div class="alert alert-danger" role="alert"><%= alert %></div><% end %>
<% if @navbar %>
	<header>
		<div class="container">
			<h1><a href="/"><%= image_tag 'logoyorescato.png' %></a></h1>
			<nav class="menu-top">
				<ul>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">- Listar -<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><%= link_to "Especies", species_index_path() %></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to "Santuarios", shrines_path() %></li>
						</ul>
					</li>
					<li>
						<form action="">
							<input type="text" class="search-field" placeholder="Buscar">
						</form>
					</li>
<<<<<<< HEAD
					
					<li>
						<%= link_to "Ingresar" %>
=======
					<% if user_signed_in? %>
					<li><%= link_to current_user.email, edit_user_registration_path %></li>
					<li>
						<%= link_to "Salir", destroy_user_session_path, method: :delete %>
					</li>
					<% else %>
					<li>
						<%= link_to "Ingresar", new_user_session_path %>
>>>>>>> 89841beef1f168e378704cb177dbef2633312f76
					</li>
					<% end %>
					<li>
						<a href="" class="donate-button">Donate</a>
					</li>
				</ul>
			</nav>
		</div>
	</header>
<% end %>
 	<%= yield %>
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-4 column-4">
					<h3>Yorescato</h3>
										
				</div>
				<div class="col-lg-4 col-md-4 col-sm-4 column-4">
					<h3>Siguenos en:</h3>
					<div class="socials-icon">
						<a href="https://www.facebook.com/yorescato" class="circle icon facebook-ico" target="_blank"></a>
						<a href="https://twitter.com/YoRescato" class="circle icon twitter-ico" target="_blank"></a>
						<a href="https://google.com/+Yorescatoa" class="circle icon google-ico" target="_blank"></a>
						<a href="https://www.youtube.com/channel/UC2dnaT5-hVlGCAjs3x5NL4g" class="circle icon youtube-ico" target="_blank"></a>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-4 column-4">
					<h3>Contactanos</h3>
					<div class="contact-button">
						<a href="" class="icon contact-ico">Envianos un E-mail</a>
					</div>
				</div>
			</div>
			<p>&copy; yorescato</p>			
		</div>
	</footer>
</div>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script>
$(function(){


var mapStyle = [
  //omitted for brevity but find nice one here: http://snazzymaps.com/
  {
        "featureType": "administrative",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#444444"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "all",
        "stylers": [
            {
                "color": "#f3f3f3"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "all",
        "stylers": [
            {
                "saturation": -100
            },
            {
                "lightness": 45
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "labels.icon",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "all",
        "stylers": [
            {
                "color": "#46bcec"
            },
            {
                "visibility": "on"
            }
        ]
    }
];

var handler = Gmaps.build('Google');
handler.buildMap({ 
    internal: {id: 'multi_markers'}, 
    provider: {
      zoom:      5,
      styles:    mapStyle
    }}, function(){
  var markers = handler.addMarkers([
    { lat: '-10.9965942', lng: '-76.3289941,17z'},
    { lat: '-17.1470818', lng: '-71.8615801,17z'},
    { lat: '-13.5773495', lng: '-72.886993,17z'},
    { lat: '-3.4252266', lng: '-80.2711588,17z'},
    { lat: '-13.1673522', lng: '-72.5452274,17z'},
    { lat: '-6.4852423', lng: '-79.7736306,17z'},
    { lat: '-5.1570234', lng: '-79.3127543,17z'}
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
});
</script>
<script>
	
	function setDimensions(){
		var windowsHeight = $(window).height();
		$('.landing').css('height', windowsHeight + 'px');
	}

	setDimensions();

	//when resizing the site, we adjust the heights of the image
	$(window).resize(function() {
		setDimensions();
	});

</script>
<!--
Font generated by <a href="http://www.flaticon.com">flaticon.com</a>
 under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY</a>. The authors are: <a href="http://www.freepik.com">Freepik</a>, <a href="http://www.danielbruce.se">Daniel Bruce</a>, <a href="http://www.elegantthemes.com">Elegant Themes</a>, <a href="http://www.simpleicon.com">SimpleIcon</a>.
 -->
</body>
</html>